services:
  # 1. Backend Web Service (Socket.IO + Express)
  - type: web
    name: Youtube-watchTogether-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false

  # 2. Frontend Static Site (Vite React)
  - type: web
    name: Youtube-watchTogether-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_SERVER_URL
        sync: false
